name: Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: true

    - name: Install pkg requirements
      uses: awalsh128/cache-apt-pkgs-action@latest
      with:
        packages: gcc make xorg libxext-dev libbsd-dev
        version: 1.0

    - name: Test
      run: make test
